.github/workflows/CI.yml
package.json

This PR adds a CI workflow to verify pull requests.

[FSK-21]: Configure GitHub Action

---

.github/workflows/CI.yml
configs/cspell/charity.txt
src/App.tsx
src/main.tsx

This PR changes the CI workflow's trigger to `pull_request`

[FSK-21]: Fix CI Trigger

---

configs/cspell/charity.txt
index.html
package-lock.json
package.json
src/App.tsx
src/main.tsx

[FKS-15] : Configure UI framework

---

.eslintrc.json
configs/cspell/charity.txt
package-lock.json
package.json
src/main.tsx

this pr adds type check eslint rule

[FSK-38]: Add Type Check ESlint Rules

---

.github/workflows/CI.yml
configs/cspell/charity.txt
package-lock.json
package.json

this pr integrates chromatic with the project

[FSK-20]: Integrate Chromatic

---

index.html

This PR solve mixed content issue.

[FSK-15]: Fix Font Mixed Content Issue

---

package.json
scripts/pr

[FSK-41]: Add PR Script

---

scripts/pr

[FSK-43]: Fix Pr Script Typo

---

.github/workflows/CI.yml

this PR fixes chromatic CI setup.

[FSK-42]: Fix Chromatic CI Setup

---

.github/workflows/CI.yml

This PR fix CI build and adds record key to CI workflow.

[FSK-16]: Fix Cypress Record Key Issue

---

package.json

This PR adds env to storybook.

[Hotfix]: Add Env To Storybook

---

.storybook/main.cjs
.storybook/preview-head.html
.storybook/preview.tsx
package-lock.json
package.json

* Remove deprecated storybook addon
* Add RLT attribute to the documentElement

[Hotfix]: Add RTL Support for Storybooks

---

package-lock.json

[Hotfix]: Fix Package Lock

---

.github/workflows/CI.yml

This PR add caching for installing dependencies in CI workflow.

[Hotfix]: Add Caching To CI Workflow

---

.github/workflows/CI.yml

[Hotfix]: Remove Ci Caching

---

src/Routes.tsx
src/components/FamilyEmptyState/FamilyEmptyState.tsx
src/components/FamilyEmptyState/index.ts
src/components/index.ts
src/pages/index.ts

This PR adds family empty state.

[Hotfix]: Add Family Empty State

---

.github/workflows/CI.yml
package.json
src/components/molecules/Breadcrumbs/Breadcrumbs.spec.ts
src/components/molecules/Breadcrumbs/Breadcrumbs.tsx
src/components/organisms/Header/DashboardHeader.tsx
src/data-layer/operations/__generated__/typesAndHooks.ts
src/data-layer/operations/mutations/CreateProject.mutation.graphql
src/data-layer/operations/queries/AdminList.query.graphql
src/router/index.ts
src/router/useMatches.tsx

Current breadcrumbs component doesn't work.

[Hotfix]: Fix Breadcrumbs

---

.github/workflows/CI.yml
cypress/e2e/createFamily.cy.ts
cypress/e2e/createProject.cy.ts
src/components/CreateFamily/FamilyButton/CreateFamilyButton.tsx
src/components/CreateFamily/FamilyForm/CreateFamilyForm.cy.tsx
src/components/CreateFamily/FamilyForm/CreateFamilyForm.tsx
src/components/CreateFamily/FamilyForm/CreateFamilyModal.cy.tsx
src/components/CreateFamily/FamilyForm/CreateFamilyModal.tsx
src/components/CreateProject/ProjectButton/CreateProjectButton.cy.tsx
src/components/CreateProject/ProjectButton/CreateProjectButton.tsx
src/components/CreateProject/ProjectForm/CreateProjectForm.tsx
src/components/CreateProject/ProjectForm/CreateProjectModal.cy.tsx
src/components/CreateProject/ProjectForm/CreateProjectModal.tsx
src/components/CreateProject/ProjectForm/index.ts
src/components/atoms/NavLink/NavLink.tsx

This PR syncs test id in all tests.

[Hotfix]: Sync Test Id In All Tests

---

@types/route.d.ts
package-lock.json
src/components/organisms/Header/DashboardHeader.tsx
src/messages.ts
src/pages/Dashboard/Families/FamilyDetail/FamilyDetail.tsx

This PR fixes Family detail route and fields.

[Hotfix]: Fix Family Detail

---

.github/workflows/CI.yml
cypress.config.ts
cypress/e2e/authorization.cy.ts
cypress/e2e/createFamily.cy.ts
cypress/e2e/createProject.cy.ts
cypress/e2e/login.cy.ts
cypress/e2e/logout.cy.ts
cypress/support/e2e.ts
package-lock.json
package.json
src/components/LogoutModal/LogoutModal.stories.tsx
src/components/LogoutModal/LogoutModal.tsx
src/components/LogoutModal/index.ts
src/components/atoms/NavLink/ExitNavLink.stories.tsx
src/components/atoms/NavLink/ExitNavLink.tsx
src/components/atoms/NavLink/NavLink.stories.tsx
src/components/atoms/NavLink/NavLink.tsx
src/components/atoms/NavLink/NavLinks.stories.tsx
src/components/atoms/NavLink/NavLinks.tsx
src/components/atoms/NavLink/index.ts
src/components/organisms/Sidebar/SideBar.tsx
src/data-layer/index.ts
src/design/icons/Exit.svg
src/design/icons/index.ts
src/messages.ts
tsconfig.json

- Logout Modal has been implemented.
- Exit button has been implemented.
- Stories for LogoutModal and exit button have been added.
- E2E tests have been implemented.
Admin needs a way to log out from his/her dashboard.

[FSK-125]: Auth Logout FE Implementation

---

README.md
cypress/e2e/createProject.cy.ts
src/components/Alert/Alert.stories.tsx
src/components/Alert/Alert.tsx
src/components/Alert/index.ts
src/components/CreateProject/ProjectForm/CreateProjectForm.tsx
src/components/Notification/showNotification.ts
src/components/atoms/NavLink/ExitNavLink.tsx
src/design/theme/theme.ts
src/pages/Login/Login.tsx
src/pages/Login/LoginForm.tsx

- Alert component has been added
- Input minHeight has been removed from theme.ts
- Notification styles have been modified
- Unnecessary styles have been removed
Our implementations of UI weren't the same as UI

[Hotfix]: Sync Implementation With Design

---

scripts/pr

This PR makes pr script work with linear.

[Hotfix]: Make PR Script Work With Linear

---

src/Routes.tsx
src/components/FamilyList/FamilyTable/FamilyTableRow.tsx
src/components/ProjectList/ProjectList.cy.tsx
src/components/ProjectList/ProjectList.stories.tsx
src/components/ProjectList/ProjectList.tsx
src/components/ProjectList/ProjectTable/ProjectTable.cy.tsx
src/components/ProjectList/ProjectTable/ProjectTable.stories.tsx
src/components/ProjectList/ProjectTable/ProjectTable.tsx
src/components/ProjectList/ProjectTable/ProjectTableRow.tsx
src/components/ProjectList/ProjectTable/index.ts
src/components/ProjectList/index.ts
src/components/atoms/ActionButton/ActionButton.cy.tsx
src/components/atoms/ActionButton/ActionButton.tsx
src/components/atoms/ActionButton/index.ts
src/components/atoms/index.ts
src/components/index.ts
src/messages.ts

- Create `ProjectList` component.
- Create `ProjectTable` component.
- Add component test and storybook.
- Make `ActionButton` reusable.

[FSK-116]: List Of Projects Page Implementation

---

configs/cspell/charity.txt
scripts/pr

[Hotfix]: Update The PR Script

---

configs/cspell/charity.txt

[Hotfix]: Fix Cspell

---

@types/mantine.d.ts
app/pages/Dashboard/Families/FamilyDetail/FamilyDetail.tsx
libs/design/DashboardCard/DashboardCard.tsx
libs/design/DetailCard/DetailCard.tsx
libs/design/Tabs/Tabs.stories.tsx
libs/design/Tabs/Tabs.tsx
libs/design/Tabs/index.ts
libs/design/index.ts

This PR householders identity page layout.

[FS-189]: Householder Identity Page Layout

---

app/components/CreateProject/ProjectForm/CreateProjectForm.tsx
app/components/HouseholderForm/HouseholderIdentityForm.cy.tsx
app/components/HouseholderForm/HouseholderIdentityForm.ids.ts
app/components/HouseholderForm/HouseholderIdentityForm.stories.tsx
app/components/HouseholderForm/HouseholderIdentityForm.tsx
app/messages.ts
app/pages/Dashboard/Families/FamilyDetail/FamilyDetail.tsx
configs/cspell/charity.txt
cypress/e2e/api.ts
cypress/e2e/householderIdentity.cy.ts
cypress/fixtures/householder.ts
libs/data-layer/api.ts
libs/data-layer/operations/mutations/index.ts
libs/data-layer/operations/mutations/useCreateFamilyMutation.ts
libs/data-layer/operations/mutations/useCreateProjectMutation.ts
libs/data-layer/operations/mutations/useMutation.ts
libs/data-layer/operations/mutations/useUpsertHouseholder.ts
libs/domain/Country.ts
libs/domain/Gender.ts
libs/domain/HouseholderIdentity.ts
libs/domain/Religions.ts
libs/domain/index.ts
package-lock.json
package.json

This PR householders identity api integration.

[FS-179]: Householder Identity Api Integration

---

README.md
configs/cspell/charity.txt
package.json
scripts/e2e-pick

Add E2E Pick Script

---

app/components/DeleteFamilyModal/DeleteFamilyModal.tsx
app/components/FamilyList/FamilyTableRow.tsx
app/messages.ts
app/pages/Dashboard/Families/FamilyDetail/FamilyDetail.tsx
libs/data-layer/api.ts
libs/data-layer/operations/mutations/index.ts
libs/data-layer/operations/mutations/useDeleteFamilyMutation.ts

- Create `DeleteFamilyMutation`.
- Integrate the mutation hook with family buttons. 
- Add failure and success feedback.

[FS-200]: Delete Family Api Integration

---

.eslintrc.js
@types/vite-env.d.ts
app/components/CreateProject/CreateProjectForm/CreateProjectForm.tsx
app/components/DeleteFamilyModal/DeleteFamilyModal.tsx
app/components/FamilyList/FamilyTableRow.tsx
app/components/HouseholderDetail/HouseholderDetail.tsx
app/components/HouseholderForm/HouseholderForm.tsx
app/main.tsx
app/messages.ts
app/pages/Dashboard/Families/FamilyDetail/FamilyDetail.tsx
configs/cspell/charity.en.txt
configs/husky/pre-push
configs/vite/cypressAliases.ts
cypress/fixtures/householder.ts
libs/auth/AuthGuard.tsx
libs/auth/GuestGuard.tsx
libs/config/config.ts
libs/data-layer/apollo/createApolloClient.ts
libs/debug/Debug.spec.ts
libs/debug/Debug.ts
libs/debug/index.ts
libs/design/Header/DashboardHeader.tsx
libs/design/README.md
libs/domain/ServerErrors.ts
package-lock.json
package.json
scripts/spell
tsconfig.json

[FS-211]: Add Debug Module

---

.cspell.json
libs/domain/Schema.ts
libs/domain/name.spec.ts

[FS-212]: Name Regex Problem

---

libs/design/Select/Select.tsx

This PR fixes select readonly state not being peresent.

[FS-216]: Fix Select Readonly State

---

cypress/e2e/login.cy.ts

This PR fixes issue with finding the proper submit button on login test

[Hotfix]: Fix Login E2E Test

---

app/components/HouseholderForm/HouseholderForm.ids.ts
app/components/HouseholderForm/HouseholderForm.tsx
app/messages.ts
app/pages/Dashboard/Households/HouseholdDetail/HouseholdDetail.tsx
libs/icons/index.ts
package-lock.json
package.json

This PR fixes householders identity information edit.

[FS-223]: Householder Identity Information Edit

---

app/Routes.tsx
app/components/CreateHousehold/CreateHouseholdButton/CreateHouseholdButton.tsx
app/components/CreateHousehold/CreateHouseholdForm/CreateHouseholdForm.cy.tsx
app/components/CreateHousehold/CreateHouseholdForm/CreateHouseholdForm.tsx
app/components/CreateHousehold/CreateHouseholdModal/CreateHouseholdModal.tsx
app/components/DeleteHouseholdModal/DeleteHouseholdModal.tsx
app/components/HouseholdEmptyState/HouseholdEmptyState.tsx
app/components/HouseholdList/HouseholdList.tsx
app/components/HouseholdList/HouseholdTableRow.tsx
app/components/InformationBadge/InformationBadge.tsx
app/components/SeverityBadge/SeverityBadge.tsx
app/messages.ts
app/pages/Auth/Login/LoginForm.tsx
app/pages/Dashboard/Households/HouseholdDetail/HouseholdDetail.tsx
app/pages/Dashboard/Households/Households.stories.tsx
app/pages/Dashboard/Households/Households.tsx
cypress/e2e/createHousehold.cy.ts
cypress/e2e/draftHouseholder.cy.ts
cypress/e2e/householdList.cy.ts
cypress/support/commands/createHousehold.command.ts
libs/data-layer/operations/mutations/useCreateHouseholdMutation.ts
libs/data-layer/operations/queries/useHouseholdListQuery.ts
libs/design/Breadcrumbs/Breadcrumbs.stories.tsx
libs/design/Header/DashboardHeader.stories.tsx
libs/design/NavLink/NavLink.stories.tsx
libs/design/Sidebar/Sidebar.ids.ts
libs/design/Sidebar/Sidebar.tsx
libs/design/Table/Table.stories.tsx
libs/domain/Household.ts
libs/router/AppRoutes.ts

This PR renames families to households.

[FS-224]: Rename Families To Households

---

libs/design/Tabs/Tabs.tsx
libs/router/index.ts
libs/router/useHash.tsx

[FS-226]: Connect Tabs To Url

---

app/components/ProjectActionButton/ProjectActionButton.cy.tsx
app/components/ProjectActionButton/ProjectActionButton.stories.tsx
app/components/ProjectActionButton/ProjectActionButton.tsx
app/components/ProjectActionButton/index.ts
app/components/ProjectList/ProjectTableRow.tsx
libs/router/AppRoutes.ts

This PR adds action button to project List.

[Hotfix]: Add Project ActionButton

---

app/pages/Dashboard/DashboardLayout.tsx
libs/design/Sidebar/Sidebar.tsx
libs/design/theme/theme.ts

This PR Fixes the sidebar scrolling layout issue.

[FS-217]: Fix Issue With Exit Button And Scrolling

---

app/messages.ts
app/pages/Dashboard/DashboardLayout.tsx
app/pages/Dashboard/Households/CreateHousehold/CreateHouseholdForm/CreateHouseholdForm.tsx
app/pages/Dashboard/Households/HouseholdDetail/HouseholdDetail.tsx
app/pages/Dashboard/Households/HouseholdList/HouseholdTableRow.tsx
app/pages/Dashboard/Projects/CreateProject/CreateProjectForm/CreateProjectForm.tsx
app/pages/GraphiQL.tsx
libs/api-client/types.ts
libs/api-client/useMutation.ts
libs/data-layer/ApiOperations.ts
libs/data-layer/operations/mutations/index.ts
libs/data-layer/operations/mutations/useCompleteHousehold.ts
libs/data-layer/operations/mutations/useDeleteHouseholdMutation.ts
libs/design/theme/theme.ts
libs/icons/index.ts

This PR marks a household as completed.

[FS-221]: Mark A Household As Completed

---

app/components/MemberForm/MemberForm.cy.tsx
app/components/MemberForm/MemberForm.tsx
app/pages/Dashboard/Households/CreateHousehold/CreateHouseholdButton/CreateHouseholdButton.cy.tsx
app/pages/Dashboard/Households/CreateHousehold/CreateHouseholdModal/CreateHouseholdModal.cy.tsx
app/pages/Dashboard/Projects/CreateProject/CreateProjectForm/CreateProjectForm.tsx
libs/design/Date/DateSummery.stories.tsx

This PR improves the UX for creating a project.

[FS-232]: CreateProject UX Improvement

---

README.md

This pr fixes the wrong link in the README file.

[Hotfix]: Fix Wrong Link in the Readme

---

app/components/InformationBadge/InformationBadge.stories.tsx
app/components/InformationBadge/InformationBadge.tsx
app/components/MemberForm/MemberForm.tsx
app/pages/Dashboard/Households/HouseholdDetail/HouseholdDetail.tsx
app/pages/Dashboard/Households/HouseholdList/HouseholdTableRow.tsx
libs/data-layer/ApiOperations.ts
libs/data-layer/operations/fragments/member.mapper.ts
libs/domain/ApiSchema.ts
libs/fixtures/ApiMemberListFixture.ts

This PR implements member status.

[FS-199]: Implement Member Status

---

app/messages.ts

This PR fixes family creation message.

[FS-234]: Fix Family Creation Message

---

app/components/HouseholderForm/HouseholderForm.tsx
app/components/SeverityBadge/SeverityBadge.tsx
app/components/index.ts
app/messages.ts
app/pages/Dashboard/Households/HouseholdDetail/HouseholdDetail.ids.ts
app/pages/Dashboard/Households/HouseholdDetail/HouseholdDetail.tsx
app/pages/Dashboard/Projects/ProjectDetail/ProjectDetail.tsx
libs/api-client/useQuery.ts
libs/data-layer/ApiOperations.ts
libs/data-layer/operations/mutations/index.ts
libs/data-layer/operations/mutations/useEditHouseholdMutation.ts
libs/data-layer/operations/mutations/useUpdateHouseholdMutation.ts
libs/design/DetailCard/DetailCard.tsx
libs/design/Select/ControlledSelect.tsx
libs/design/TextInput/TextInput.tsx
libs/design/TextInput/useReadonlyInputStyles.ts
libs/domain/Household.ts

This PR updates a household general information.

[FS-220]: Update A Household General Information

---

app/Dashboard/Households/HouseholdDetail/_components/MemberForm/MemberForm.tsx
libs/design/DateInput/DateInput.tsx

This PR fixes some issues in member form.

[FS-199]: Fix Date Picker Layout

---

app/Dashboard/Households/HouseholdDetail/_components/MemberForm/MemberForm.tsx
libs/design/DashboardCard/CollapsibleDashboardCard.stories.tsx
libs/design/DashboardCard/CollapsibleDashboardCard.tsx
libs/design/DashboardCard/DashboardCard.stories.tsx
libs/design/DashboardCard/DashboardCard.tsx
libs/design/DashboardCard/index.ts

[FS-199]: Imprvoe Member Form

---

app/Dashboard/Households/HouseholdDetail/HouseholdDetail.ids.ts
app/Dashboard/Households/HouseholdDetail/HouseholdDetail.tsx
app/messages.ts
libs/data-layer/ApiOperations.ts
libs/data-layer/operations/fragments/household.fragments.ts
libs/data-layer/operations/fragments/household.mapper.ts
libs/design/Select/ControlledSelect.tsx
libs/domain/ApiSchema.ts
libs/domain/Household.ts
libs/domain/Householder.ts
libs/domain/Schema.ts
libs/fixtures/HouseholdListFixture.ts

This PR adds membercount field in householddetail.

[FS-220]: Add MemberCount Field In HouseholdDetail

---

cypress/e2e/api.ts
cypress/e2e/householdDetail.cy.ts
cypress/fixtures/household.ts
cypress/fixtures/project.ts

This PR adds household detail e2e test cases.

[FS-124]: Add Household Detail E2e Test Cases

---

.github/workflows/CI.yml
@types/vite-env.d.ts
app/Dashboard/Projects/ProjectDetail/_components/CreateProjectDocument/CreateProjectDocumentForm/CreateProjectDocumentForm.tsx
cypress.config.ts
libs/config/config.ts
libs/design/FileUpload/ControlledFileUpload.tsx
libs/design/FileUpload/File.tsx
libs/design/FileUpload/FileState.ts
libs/design/FileUpload/FileUpload.stories.tsx
libs/design/FileUpload/FileUpload.tsx
libs/domain/Document.ts
libs/file-storage-api/fileStorageApi.ts
libs/file-storage-api/index.ts
package.json
pnpm-lock.yaml
tsconfig.json

This PR projects document api integration.

[FS-281]: Project Document Api Integration
